version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: whiteboard
      POSTGRES_USER: wbb_user
      POSTGRES_PASSWORD: wbb_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wbb_user -d whiteboard"]
      interval: 1s
      timeout: 5s
      retries: 50

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=whiteboard;Username=wbb_user;Password=wbb_password
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./WhiteboardApp.sln:/app/WhiteboardApp.sln

  # Development service for running dotnet commands
  dotnet-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    working_dir: /app
    profiles:
      - dev
    command: sleep infinity

volumes:
  postgres_data:

